# Generated by Django 2.1 on 2019-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=5)),
                ('id_card_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('phone_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('phone_no_2', models.CharField(db_index=True, max_length=20, null=True)),
                ('passport_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('home_address', models.CharField(max_length=200, null=True)),
                ('photo_url', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('brand_chinese_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, null=True)),
                ('house_no', models.CharField(max_length=50)),
                ('house_address', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(default='man', max_length=5)),
                ('relation_type', models.CharField(max_length=20)),
                ('id_card_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('phone_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('phone_no_2', models.CharField(db_index=True, max_length=20, null=True)),
                ('passport_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('home_address', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, null=True)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('company_org_no', models.CharField(db_index=True, max_length=200, null=True)),
                ('company_phone_no', models.CharField(db_index=True, max_length=20, null=True)),
                ('company_address', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=20)),
            ],
        ),
    ]
