# Generated by Django 2.1 on 2019-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('card_no', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(db_index=True, max_length=50, null=True)),
                ('order_status', models.CharField(choices=[('init', '初始状态'), ('wait_pay', '待付款状态'), ('finish', '完成状态')], db_index=True, default='init', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=50)),
            ],
        ),
    ]
